In [34]:
#null vector of size 10 but the fifth value is 1

In [35]:
import numpy as np


In [36]:
a = np.zeros(shape = 10,dtype = int)

In [37]:
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
a[5] = 1

In [39]:
a

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [40]:
#create a vector with values ranging from 10 to 49

In [41]:
a = np.arange(10,49)

In [42]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [43]:
#create a 3*3 matrix with values ranging from 0 to 8

In [57]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#find the indices of non zero elements from [1,2,0,0,4,0]

In [58]:
a = np.array([1,2,0,0,4,0])

In [60]:
a != 0

array([ True,  True, False, False,  True, False])

In [61]:
a = np.where(a!=0)

In [62]:
a

(array([0, 1, 4], dtype=int64),)

In [ ]:
#create a 10*10 array with random values and find the maximum and minimum values

In [63]:
a = np.random.rand(10,10)

In [64]:
a

array([[0.80242816, 0.83801326, 0.27104081, 0.71595961, 0.34557044,
        0.89022588, 0.52527388, 0.7851363 , 0.25981119, 0.44795318],
       [0.25514208, 0.03119018, 0.65240306, 0.87265306, 0.90446891,
        0.21662057, 0.98301586, 0.84417538, 0.9492175 , 0.32462269],
       [0.35373306, 0.93405955, 0.11922642, 0.92443931, 0.29071909,
        0.8990904 , 0.10643945, 0.76244293, 0.05487037, 0.95962298],
       [0.00211286, 0.39531565, 0.3008364 , 0.43909139, 0.72799886,
        0.24108145, 0.02246653, 0.78137308, 0.52099513, 0.70573502],
       [0.90999018, 0.13493986, 0.27072205, 0.87679707, 0.42834948,
        0.64860656, 0.31231352, 0.41840282, 0.97138598, 0.09728316],
       [0.04681455, 0.94860691, 0.57667027, 0.32264491, 0.943968  ,
        0.82218816, 0.66686956, 0.00267733, 0.6538145 , 0.76021809],
       [0.18880786, 0.69368531, 0.73028349, 0.10452845, 0.50023165,
        0.11001737, 0.59457625, 0.8374706 , 0.76183811, 0.11899791],
       [0.60293823, 0.63163985, 0.1390978

In [65]:
a = np.random.rand(10,10).max(), np.random.rand(10,10).min()

In [66]:
a

(0.991134092453282, 0.00601430810544179)

In [ ]:
#create a random vector of size 30 and find the mean value

In [67]:
a = np.random.rand(30)

In [68]:
a

array([0.73998524, 0.15109473, 0.90293607, 0.17460997, 0.0750374 ,
       0.0460573 , 0.9076966 , 0.56431221, 0.95409431, 0.24845044,
       0.90654777, 0.35919762, 0.81298828, 0.73109142, 0.79554024,
       0.60135132, 0.03439252, 0.11681922, 0.57024698, 0.16812518,
       0.64611867, 0.23273367, 0.45150087, 0.18534143, 0.76822217,
       0.58240019, 0.48574652, 0.01202511, 0.63951476, 0.88190826])

In [69]:
a = np.random.rand(30).mean()

In [70]:
a

0.4981960757285696